# Generated by Django 3.2.12 on 2024-11-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI_vBrainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='TeamMembers',
        ),
    ]
