# Generated by Django 3.2.12 on 2024-11-15 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI_vBrainApp', '0003_auto_20241112_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMembers',
            new_name='Team',
        ),
    ]
